export type {
  RegistryIndexItem,
  RegistryIndex,
  RegistrySummary,
  ComponentCategory,
  ComponentItem,
  RegistryItemKind,
  CuratedUiCollectionDefinition,
  CuratedUiCollection,
} from "@/lib/shadcn/registry-service";
export {
  buildRegistryIndexUrl,
  buildRegistryItemUrl,
  buildPreviewImageUrl,
  fetchRegistryIndex,
  fetchRegistryIndexWithOptions,
  fetchRegistrySummary,
  fetchRegistryItem,
  fetchRegistryItemWithOptions,
  getRegistryItemsByCategory,
  getBlocksByCategory,
  getComponentsByCategory,
  searchBlocks,
  FEATURED_BLOCKS,
  CURATED_UI_COLLECTIONS,
  getCuratedUiCollections,
} from "@/lib/shadcn/registry-service";
