"""
Backoffice page: Dossiers (capability-driven, v2 layout).

Reads the new minimal layout:
    data/dossiers/hard/<id>/manifest.json
    data/dossiers/soft/<id>/manifest.json
    data/dossiers/_index/capability-map.json

Lets you:
- Browse all dossiers (hard + soft) with the 4-field summary.
- Edit a manifest in-place (text area, validates JSON before save).
- Trigger an AI-curation run from a template-references repo (single dossier
  at a time, not batch).
- Rebuild capability-map.json from the manifests.

Source-of-truth for the format: docs/architecture/dossier-system.md
"""
from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import streamlit as st


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DOSSIER_ROOT = REPO_ROOT / "data" / "dossiers"
HARD_ROOT = DOSSIER_ROOT / "hard"
SOFT_ROOT = DOSSIER_ROOT / "soft"
INDEX_ROOT = DOSSIER_ROOT / "_index"
CAPABILITY_MAP_PATH = INDEX_ROOT / "capability-map.json"
TEMPLATE_REFS_ROOT = REPO_ROOT / "data" / "template-references" / "repos"

REQUIRED_FIELDS = ("id", "label", "capability", "codeFidelity", "complexity", "summary", "lastVerified")


def _load_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def _save_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _list_dossier_dirs(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return sorted(d for d in root.iterdir() if d.is_dir() and not d.name.startswith("_"))


def _walk_all_dossiers() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for klass, root in (("hard", HARD_ROOT), ("soft", SOFT_ROOT)):
        for d in _list_dossier_dirs(root):
            manifest = _load_json(d / "manifest.json")
            if not manifest:
                continue
            manifest["_class"] = klass
            manifest["_path"] = str(d.relative_to(REPO_ROOT))
            out.append(manifest)
    return out


def _validate_manifest(data: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for f in REQUIRED_FIELDS:
        if f not in data:
            errors.append(f"missing required field: {f}")
    if "codeFidelity" in data and data["codeFidelity"] not in ("verbatim", "rewritable"):
        errors.append("codeFidelity must be 'verbatim' or 'rewritable'")
    if "complexity" in data and data["complexity"] not in ("simple", "medium", "advanced"):
        errors.append("complexity must be 'simple' | 'medium' | 'advanced'")
    if "id" in data and not isinstance(data["id"], str):
        errors.append("id must be a string")
    return errors


def _rebuild_capability_map(dossiers: list[dict[str, Any]]) -> dict[str, Any]:
    by_cap: dict[str, list[str]] = {}
    for d in dossiers:
        cap = d.get("capability") or "uncategorized"
        by_cap.setdefault(cap, []).append(d["id"])
    for cap in by_cap:
        by_cap[cap].sort()
    return {
        "$comment": "Generated by backoffice/pages/dossiers.py. Read by tooling; runtime walks data/dossiers/{hard,soft}/ directly.",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "capabilities": dict(sorted(by_cap.items())),
    }


def _section_overview(dossiers: list[dict[str, Any]]) -> None:
    st.subheader("Översikt")
    hard = [d for d in dossiers if d["_class"] == "hard"]
    soft = [d for d in dossiers if d["_class"] == "soft"]
    cols = st.columns(4)
    cols[0].metric("Totalt", len(dossiers))
    cols[1].metric("Hard", len(hard))
    cols[2].metric("Soft", len(soft))
    caps = {d.get("capability", "?") for d in dossiers}
    cols[3].metric("Capabilities", len(caps))


def _section_list(dossiers: list[dict[str, Any]]) -> None:
    st.subheader("Alla dossiers")
    if not dossiers:
        st.info("Inga dossiers ännu. Skapa en under `data/dossiers/hard/` eller `soft/`, eller använd AI-kurations-tabben nedan.")
        return
    rows: list[dict[str, Any]] = []
    for d in dossiers:
        rows.append({
            "id": d.get("id"),
            "class": d["_class"],
            "capability": d.get("capability"),
            "codeFidelity": d.get("codeFidelity"),
            "complexity": d.get("complexity"),
            "default": "✓" if d.get("defaultForCapability") else "",
            "envVars": len(d.get("envVars") or []),
            "deps": len(d.get("dependencies") or []),
            "files": len(d.get("files") or []),
            "lastVerified": d.get("lastVerified"),
        })
    rows.sort(key=lambda r: (r["class"], r["capability"] or "", r["id"]))
    st.dataframe(rows, width="stretch", hide_index=True)


def _section_edit(dossiers: list[dict[str, Any]]) -> None:
    st.subheader("Redigera manifest")
    if not dossiers:
        return
    options = {f"{d['_class']}/{d['id']}": d for d in dossiers}
    pick_key = st.selectbox("Välj dossier", list(options.keys()))
    if not pick_key:
        return
    chosen = options[pick_key]
    manifest_path = REPO_ROOT / chosen["_path"] / "manifest.json"
    raw = manifest_path.read_text(encoding="utf-8")
    edited = st.text_area("manifest.json", value=raw, height=400, key=f"edit_{pick_key}")
    if st.button("Spara", type="primary", key=f"save_{pick_key}"):
        try:
            parsed = json.loads(edited)
        except json.JSONDecodeError as exc:
            st.error(f"Ogiltig JSON: {exc}")
            return
        errors = _validate_manifest(parsed)
        if errors:
            st.error("Validering misslyckades:\n" + "\n".join(f"- {e}" for e in errors))
            return
        manifest_path.write_text(json.dumps(parsed, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        st.success(f"Sparat {manifest_path.relative_to(REPO_ROOT)}")
        st.cache_data.clear()


def _section_capability_map(dossiers: list[dict[str, Any]]) -> None:
    st.subheader("Capability map")
    st.caption(
        "Översikt över vilka dossiers som är registrerade per capability. "
        "Brief-LLM:n deklarerar `requestedCapabilities` och varje capability "
        "matchar mot exakt en dossier (eller ingen om kapabiliteten saknas)."
    )
    current = _load_json(CAPABILITY_MAP_PATH)
    fresh = _rebuild_capability_map(dossiers)
    diff = (current or {}).get("capabilities") != fresh["capabilities"]
    if diff:
        st.warning("`capability-map.json` är inte i synk med manifests. Klicka för att bygga om.")
    if st.button("Bygg om capability-map.json"):
        _save_json(CAPABILITY_MAP_PATH, fresh)
        st.success(f"Skrev {CAPABILITY_MAP_PATH.relative_to(REPO_ROOT)}")
    st.json(fresh["capabilities"])


def _list_template_refs() -> list[str]:
    if not TEMPLATE_REFS_ROOT.exists():
        return []
    return sorted(d.name for d in TEMPLATE_REFS_ROOT.iterdir() if d.is_dir())


def _run_curate(reference_id: str, target_class: str, target_id: str) -> tuple[bool, str]:
    cmd = [
        "npx",
        "tsx",
        "scripts/dossiers/curate-from-reference.ts",
        f"--reference={reference_id}",
        f"--class={target_class}",
        f"--id={target_id}",
    ]
    try:
        result = subprocess.run(
            cmd, cwd=str(REPO_ROOT), capture_output=True, text=True, check=False, timeout=300,
        )
        out = (result.stdout or "") + (result.stderr or "")
        return result.returncode == 0, out
    except subprocess.TimeoutExpired:
        return False, "Kurations-skriptet tog mer än 5 minuter — kör från terminal istället."
    except FileNotFoundError as exc:
        return False, f"Saknar binär: {exc}"


def _section_curate() -> None:
    st.subheader("AI-kuration från template-references")
    st.caption(
        "Pekar på en klonad mapp under `data/template-references/repos/` och låter "
        "GPT producera ett **utkast** till dossier-manifest + `instructions.md`. "
        "Granska och spara via Redigera-tabben innan dossiern går live."
    )
    refs = _list_template_refs()
    if not refs:
        st.info(
            "Inga template-references hittade. Klona ett repo manuellt till "
            f"`{TEMPLATE_REFS_ROOT.relative_to(REPO_ROOT)}/<id>/` eller kör "
            "`git clone <url> data/template-references/repos/<id>` från terminalen."
        )
        return
    cols = st.columns(3)
    with cols[0]:
        ref_id = st.selectbox("Referens-repo", refs)
    with cols[1]:
        target_class = st.radio("Klass", ["hard", "soft"], horizontal=True)
    with cols[2]:
        suggested = ref_id.replace("_", "-").replace(" ", "-").lower() if ref_id else ""
        target_id = st.text_input("Ny dossier-id", value=suggested)
    if st.button("🤖 Kurera utkast", type="primary"):
        if not target_id:
            st.error("Ange ett ID för den nya dossiern.")
            return
        with st.spinner("Kör kurations-skriptet…"):
            ok, output = _run_curate(ref_id, target_class, target_id)
        (st.success if ok else st.error)(output[-3000:])
        if ok:
            st.info(
                f"Granska och redigera `data/dossiers/{target_class}/{target_id}/` i Redigera-tabben "
                f"innan dossiern är produktionsklar."
            )


def render(ctx) -> None:  # ctx kept for backoffice signature parity
    del ctx
    st.title("Dossiers")
    st.caption(
        "Capability-driven, deterministic urval. "
        "[Format-spec](/?nav=docs) · "
        "Disk: `data/dossiers/{hard|soft}/<id>/` · Schema: `docs/schemas/strict/dossier.schema.json`."
    )

    dossiers = _walk_all_dossiers()
    tabs = st.tabs(["Översikt", "Lista", "Redigera", "Capability map", "AI-kuration"])
    with tabs[0]:
        _section_overview(dossiers)
    with tabs[1]:
        _section_list(dossiers)
    with tabs[2]:
        _section_edit(dossiers)
    with tabs[3]:
        _section_capability_map(dossiers)
    with tabs[4]:
        _section_curate()
