export type UiMessagePart = {
  type?: string;
  [key: string]: unknown;
};

export type ChatMessage = {
  id: string;
  role: "user" | "assistant";
  content: string;
  thinking?: string | null;
  isStreaming?: boolean;
  uiParts?: UiMessagePart[];
};

/**
 * Additive marker on a persisted `"user"` message that says the prompt was
 * generated by an internal process (auto-repair, F3 kick) rather than typed
 * by the user. Deliberately NOT a new role — a new role would break every
 * reader that filters `engine_messages` by `role === "user"` (F3-continuation,
 * contract-answer capture, OpenClaw context, chat history). The message keeps
 * its real content and role for every one of those consumers; only the
 * rendering layer reads this marker to avoid presenting it as something the
 * user typed (Spår 03 Steg 4 / M1).
 */
export const PROMPT_SOURCE_UI_PART_TYPE = "prompt-source";

/**
 * Legacy prefix for repair prompts persisted before `PROMPT_SOURCE_UI_PART_TYPE`
 * existed. Kept as a fallback so already-stored rows still render collapsed.
 */
const LEGACY_AUTO_REPAIR_PROMPT_PREFIX = "AUTO-FIX REQUEST";

/**
 * The synthetic prompt the F3 auto-kick sends (`handleF3Ready`,
 * use-preview-layout.ts). Lives here so the send and the reload-classifier
 * below can never drift apart: the marker is client-optimistic only, so a
 * reloaded chat is classified by EXACT content match against this sentence.
 * The kick has always sent this one fixed string, so exact match covers
 * every legacy row — a prefix match would swallow a user's own follow-up
 * that happens to start the same way (Bugbot på #1023).
 */
export const F3_KICK_PROMPT =
  "Bygg integrationer nu utifrån den finaliserade designversionen.";

function hasPromptSourceMarker(
  message: Pick<ChatMessage, "uiParts">,
  sourceKind: "autofix" | "f3-kick",
): boolean {
  return Boolean(
    message.uiParts?.some(
      (part) => part.type === PROMPT_SOURCE_UI_PART_TYPE && part.sourceKind === sourceKind,
    ),
  );
}

export function isAutoRepairPromptMessage(
  message: Pick<ChatMessage, "role" | "uiParts" | "content">,
): boolean {
  if (message.role !== "user") return false;
  if (hasPromptSourceMarker(message, "autofix")) return true;
  return message.content.trimStart().startsWith(LEGACY_AUTO_REPAIR_PROMPT_PREFIX);
}

export function isF3KickPromptMessage(
  message: Pick<ChatMessage, "role" | "uiParts" | "content">,
): boolean {
  if (message.role !== "user") return false;
  if (hasPromptSourceMarker(message, "f3-kick")) return true;
  return message.content.trim() === F3_KICK_PROMPT;
}

export interface FileNode {
  name: string;
  path: string;
  type: "file" | "folder";
  children?: FileNode[];
  content?: string;
  locked?: boolean;
}

export type ElementMapItem = {
  tag: string;
  id: string | null;
  className: string | null;
  text: string | null;
  selector: string;
  rect: { x: number; y: number; width: number; height: number };
  vpPercent: { x: number; y: number; w: number; h: number };
};

export type ElementMapResponse = {
  success: boolean;
  elements?: ElementMapItem[];
  viewport?: { width: number; height: number };
  elementCount?: number;
  collectedAt?: string;
  error?: string;
};
