import { Post } from './db';

export const mockPosts: Post[] = [
  {
    id: '1',
    slug: 'min-chokladkaka',
    title: 'Min favoritchokladkaka!',
    content: '# Min favoritchokladkaka!\n\nIdag har jag bakat den godaste chokladkakan någonsin med mamma! Den var så god att jag åt tre bitar.\n\n## Ingredienser\n- Choklad\n- Mjöl\n- Ägg\n- Socker\n\nDet var super kul att baka! Agnes hjälpte också till att röra i skålen.',
    excerpt: 'Idag har jag bakat den godaste chokladkakan någonsin med mamma!',
    author: 'zelda',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&h=600&fit=crop',
    tags: ['choklad', 'bakning', 'kul'],
    published: true,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: '2',
    slug: 'fotbollsmatch',
    title: 'Vann fotbollsmatchen!',
    content: '# Vann fotbollsmatchen!\n\nVi vann matchen idag 3-1! Jag gjorde två mål och var så glad. Hela laget jublade!\n\n## Matchen\nDet var en jättespännande match. Först låg vi efter men sedan vände vi och vann stort.\n\nJag är så tacksam för mitt lag och alla som kom och hejade på oss!',
    excerpt: 'Vi vann matchen idag 3-1! Jag gjorde två mål och var så glad.',
    author: 'blanka',
    imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&h=600&fit=crop',
    tags: ['fotboll', 'sport', 'vinst'],
    published: true,
    createdAt: '2026-01-22T14:30:00Z',
    updatedAt: '2026-01-22T14:30:00Z',
  },
  {
    id: '3',
    slug: 'pyssel-med-agnes',
    title: 'Pyssel med Agnes',
    content: '# Pyssel med Agnes\n\nIdag har Agnes och jag gjort så mycket pyssel! Vi har klippt och klistrat och ritat.\n\n## Vad vi gjorde\n- Klippte ut stjärnor\n- Målade med vattenfärg\n- Gjorde collage\n\nDet var så kul! Agnes är bästa pysselvännen!',
    excerpt: 'Idag har Agnes och jag gjort så mycket pyssel! Vi har klippt och klistrat.',
    author: 'zelda',
    imageUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&h=600&fit=crop',
    tags: ['pyssel', 'vänner', 'kreativitet'],
    published: true,
    createdAt: '2026-01-18T16:00:00Z',
    updatedAt: '2026-01-18T16:00:00Z',
  },
  {
    id: '4',
    slug: 'elevrads-mote',
    title: 'Mitt första elevrådsмöte',
    content: '# Mitt första elevrådsмöte\n\nJag hade mitt första möte som elevrådsrepresentant idag! Det var lite nervöst men också jättekul.\n\n## Vad vi pratade om\n- Nya leksaker till rasten\n- Bättre mat i matsalen\n- Fler böcker i biblioteket\n\nJag är så glad att jag fick bli vald. Jag vill göra skolan bättre för alla!',
    excerpt: 'Jag hade mitt första möte som elevrådsrepresentant idag!',
    author: 'blanka',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop',
    tags: ['skola', 'elevråd', 'ansvar'],
    published: true,
    createdAt: '2026-01-25T13:00:00Z',
    updatedAt: '2026-01-25T13:00:00Z',
  },
  {
    id: '5',
    slug: 'godis-fredag',
    title: 'Godisfredag!',
    content: '# Godisfredag!\n\nÄntligen är det fredag och det betyder GODIS! Jag fick köpa massa gott på ICA.\n\n## Mitt godis\n- Nappar\n- Geléhallon\n- Chokladkulor\n- Lösgodis mix\n\nSen sov jag i mammas säng och tittade på film. Bästa dagen!',
    excerpt: 'Äntligen är det fredag och det betyder GODIS!',
    author: 'zelda',
    imageUrl: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=800&h=600&fit=crop',
    tags: ['godis', 'fredag', 'mysigt'],
    published: true,
    createdAt: '2026-01-24T19:00:00Z',
    updatedAt: '2026-01-24T19:00:00Z',
  },
  {
    id: '6',
    slug: 'tacksamhet',
    title: 'Vad jag är tacksam för',
    content: '# Vad jag är tacksam för\n\nIdag tänkte jag på allt jag är tacksam för. Det är så mycket!\n\n## Min lista\n1. Min familj\n2. Mina vänner\n3. Fotboll\n4. Min skola\n5. Att jag är frisk\n\nDet är viktigt att vara tacksam för det man har. Det gör en glad!',
    excerpt: 'Idag tänkte jag på allt jag är tacksam för. Det är så mycket!',
    author: 'blanka',
    imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=800&h=600&fit=crop',
    tags: ['tacksamhet', 'tankar', 'glädje'],
    published: true,
    createdAt: '2026-01-19T11:00:00Z',
    updatedAt: '2026-01-19T11:00:00Z',
  },
];
