/**
 * Provision per-scaffold warm cache for pre-VM typecheck + eslint.
 *
 * Context: `src/lib/gen/preview/warm-typecheck.ts` and
 * `src/lib/gen/preview/warm-eslint.ts` are both designed fail-open and
 * return `cache_cold` unless an external provisioning step has populated
 * `tmp/sajtmaskin/typecheck-cache/<scaffoldId>/` with:
 *   - `node_modules/` (or a symlink/junction to the repo's own node_modules)
 *   - `tsconfig.json`
 *   - `eslint.config.mjs` (or .js / .ts)
 *
 * Until this script existed, no provisioning actually happened in dev, so
 * blocking typecheck and blocking lint never ran, even when the feature
 * flags were on. Empirical cost: a generated `/showcase` route shipped with
 * a TS1361 in it (2026-04-23) and only got caught after the VM had tried
 * to build it — a 118s detour.
 *
 * Scope: start with `landing-page` only (the scaffold that matches most
 * real prompts). Expand via the `SCAFFOLD_IDS` list below once disk cost
 * and latency are measured.
 *
 * Strategy: the repo already has all the dependencies the generated
 * project needs (they are a superset; the scaffold's package.json is
 * empirically a subset of root). So the cache's `node_modules` is created
 * as a **symlink (junction on Windows)** to the repo's own `node_modules`.
 * That's O(1) disk + O(1) time per scaffold and always in sync with repo
 * upgrades.
 *
 * Fallback: if symlinks/junctions fail (e.g. Windows developer mode off AND
 * running without admin), the script prints a friendly error and bails —
 * dev can retry after enabling developer mode or running `npm install` in
 * the cache dir manually. We deliberately do NOT fall back to copying
 * `node_modules` because that would silently burn 500+ MB per scaffold.
 */

import { existsSync, mkdirSync, rmSync, symlinkSync, writeFileSync, readFileSync, copyFileSync, statSync, readdirSync, lstatSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { tmpdir, platform } from "node:os";

const REPO_ROOT = resolve(__dirname, "..");
const REPO_NODE_MODULES = join(REPO_ROOT, "node_modules");
const REPO_TSCONFIG = join(REPO_ROOT, "tsconfig.json");
const REPO_ESLINT_CONFIG = join(REPO_ROOT, "eslint.config.mjs");
const REPO_ESLINT_RC_SUPPORT = join(REPO_ROOT, ".eslintignore"); // optional

const SCAFFOLD_IDS = ["landing-page"];

const CACHE_ROOT_OVERRIDE = process.env.SAJTMASKIN_PRE_VM_TYPECHECK_CACHE_ROOT;
const CACHE_ROOT = CACHE_ROOT_OVERRIDE
  ? resolve(CACHE_ROOT_OVERRIDE)
  : join(tmpdir(), "sajtmaskin", "typecheck-cache");

const args = process.argv.slice(2);
const FORCE = args.includes("--force");

type ScaffoldReport = {
  scaffoldId: string;
  cacheDir: string;
  nodeModules: "symlinked" | "already" | "failed";
  tsconfig: "written" | "skipped";
  eslintConfig: "written" | "skipped";
  durationMs: number;
};

function isJunctionOrSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
}

function ensureDir(path: string): void {
  if (!existsSync(path)) mkdirSync(path, { recursive: true });
}

function writeMinimalPackageJson(cacheDir: string, scaffoldId: string): void {
  const minimal = {
    name: `sajtmaskin-warm-cache-${scaffoldId}`,
    version: "0.0.0",
    private: true,
    description:
      "Auto-generated by scripts/provision-warm-cache.ts. Do not edit; re-run the script to refresh.",
  };
  writeFileSync(
    join(cacheDir, "package.json"),
    JSON.stringify(minimal, null, 2) + "\n",
    "utf8",
  );
}

function linkNodeModules(cacheDir: string): ScaffoldReport["nodeModules"] {
  const target = join(cacheDir, "node_modules");
  if (existsSync(target)) {
    if (FORCE) {
      // Only remove if it's a symlink (safe); we refuse to touch a real dir.
      if (isJunctionOrSymlink(target)) {
        rmSync(target, { force: true });
      } else {
        console.warn(
          `[provision-warm-cache] ${cacheDir}/node_modules exists as a real directory; --force will NOT delete it. Remove manually if stale.`,
        );
        return "already";
      }
    } else {
      return "already";
    }
  }
  try {
    // On Windows, symlinkSync requires developer mode OR admin. Passing
    // "junction" (Windows-only) avoids the privilege requirement for
    // directory targets, which is exactly what we need here.
    const type = platform() === "win32" ? "junction" : "dir";
    symlinkSync(REPO_NODE_MODULES, target, type);
    return "symlinked";
  } catch (err) {
    console.error(
      `[provision-warm-cache] Failed to symlink node_modules at ${target}: ${err instanceof Error ? err.message : String(err)}`,
    );
    console.error(
      `[provision-warm-cache] On Windows, enable Developer Mode (Settings → Privacy & security → For developers) and re-run.`,
    );
    return "failed";
  }
}

function copyConfigFile(from: string, to: string): "written" | "skipped" {
  if (!existsSync(from)) return "skipped";
  ensureDir(dirname(to));
  copyFileSync(from, to);
  return "written";
}

function provisionScaffold(scaffoldId: string): ScaffoldReport {
  const startedAt = Date.now();
  const cacheDir = join(CACHE_ROOT, scaffoldId);
  ensureDir(cacheDir);

  writeMinimalPackageJson(cacheDir, scaffoldId);
  const nodeModules = linkNodeModules(cacheDir);
  const tsconfig = copyConfigFile(REPO_TSCONFIG, join(cacheDir, "tsconfig.json"));
  const eslintConfig = copyConfigFile(
    REPO_ESLINT_CONFIG,
    join(cacheDir, "eslint.config.mjs"),
  );
  // Best-effort: copy .eslintignore if present (some setups rely on it even
  // with flat config).
  if (existsSync(REPO_ESLINT_RC_SUPPORT)) {
    copyConfigFile(REPO_ESLINT_RC_SUPPORT, join(cacheDir, ".eslintignore"));
  }

  return {
    scaffoldId,
    cacheDir,
    nodeModules,
    tsconfig,
    eslintConfig,
    durationMs: Date.now() - startedAt,
  };
}

function main(): void {
  if (!existsSync(REPO_NODE_MODULES)) {
    console.error(
      `[provision-warm-cache] Repo node_modules not found at ${REPO_NODE_MODULES}. Run \`npm install\` in the repo root first.`,
    );
    process.exit(1);
  }

  ensureDir(CACHE_ROOT);

  console.log(`[provision-warm-cache] Cache root: ${CACHE_ROOT}`);
  console.log(`[provision-warm-cache] Repo root: ${REPO_ROOT}`);
  console.log(`[provision-warm-cache] Scaffolds: ${SCAFFOLD_IDS.join(", ")}`);
  if (FORCE) console.log(`[provision-warm-cache] --force enabled`);

  const reports: ScaffoldReport[] = [];
  let anyFailed = false;
  for (const id of SCAFFOLD_IDS) {
    const report = provisionScaffold(id);
    reports.push(report);
    if (report.nodeModules === "failed") anyFailed = true;
    console.log(
      `  ${id}: nm=${report.nodeModules} tsconfig=${report.tsconfig} eslint=${report.eslintConfig} (${report.durationMs}ms)`,
    );
  }

  if (anyFailed) {
    console.error(
      `[provision-warm-cache] One or more scaffolds failed — blocking typecheck/lint will remain fail-open for those. See message above.`,
    );
    process.exit(2);
  }

  console.log(
    `[provision-warm-cache] Done. Set SAJTMASKIN_PRE_VM_TYPECHECK=1 and SAJTMASKIN_BLOCKING_ESLINT=1 in .env.local to activate blocking passes.`,
  );
}

// Guard against accidental import: this is a CLI script only.
void readdirSync;
void readFileSync;
void statSync;
main();
